### ISSUE TITLE
Validations Quiz Question #5 Has No Correct Answer

### ISSUE THREAD

**Issue by ckelly38** [learn-co-curriculum/python-p4-quiz-forms-and-validations#1]
### Canvas Link

https://learning.flatironschool.com/courses/6560/quizzes/54130

### Concern

Question 5
Which of these validations is most appropriate for making sure that a
model's title is at least 20 letters long?
ANSWER 1:
@validates('title')
def validate_title(self, key, title):
    if len(title) != 20:
        raise ValueError("title must be 20 letters.")
    return title
ANSWER 2: I don't know
ANSWER 3:
@validates('title')
def validate_title(self, key, title):
    if len(title) <= 20:
        raise ValueError("title must be 20 letters.")
    return title

- **ANSWER #3 is marked correct BUT IT IS NOT CORRECT**. At least means it includes the minimum. **But ANSWER #3 ERRORS OUT on the MINIMUM allowed length.**
- The not equals option (ANSWER #1) **includes way more than was intended** (so it is wrong and eliminated) for instance: 19 letters or less would also be acceptable. Less than zero is not possible with the length method, but if it were negative values would be included here too.
- The I don't know answer (ANSWER #2) is considered truthful but **wrong and is also eliminated**. **Really this is the closest to being correct.**

### Suggested Changes

**Get rid of the =** sign after the < in ANSWER #3 or say **excluding 20** in the question or say **has more than** 20 characters/letters. Alternatively, you could add another option to say **NONE OF THESE.**

**Comment by AlveeM** [comment]
Thanks for submitting the issue! 

The quiz was fixed in the Blueprint but it wasn't synced with your cohort due to a Canvas bug. We have manually updated your cohort instance with the fix.
